K22CNTT3-NguyenBaTruong-project2/Models/KHACH_HANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNTT3_NguyenBaTruong_project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACH_HANG()
        {
            this.DON_HANG = new HashSet<DON_HANG>();
            this.SAN_PHAM = new HashSet<SAN_PHAM>();
        }
    
        public int MaKH { get; set; }
        public string Ho_ten { get; set; }
        public string Tai_khoan { get; set; }
        public string Mat_khau { get; set; }
        public string Dia_chi { get; set; }
        public string Dien_thoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Ngay_sinh { get; set; }
        public Nullable<System.DateTime> Ngay_cap_nhat { get; set; }
        public Nullable<byte> Gioi_tinh { get; set; }
        public int Tich_diem { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DON_HANG> DON_HANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAN_PHAM> SAN_PHAM { get; set; }
    }
}

K22CNTT3-NguyenBaTruong-project2/Controllers/KHACH_HANGController.cs
using K22CNTT3_NguyenBaTruong_project2.Models;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

public class KHACH_HANGController : Controller
{
    private PhukienthucungEntities db = new PhukienthucungEntities();

    // GET: KHACH_HANG/Login
    public ActionResult Login()
    {
        return View();
    }

    // POST: KHACH_HANG/Login
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Login(string Tai_khoan, string Mat_khau)
    {
        if (string.IsNullOrWhiteSpace(Tai_khoan) || string.IsNullOrWhiteSpace(Mat_khau))
        {
            ModelState.AddModelError("", "Tài khoản và mật khẩu không được để trống");
            return View();
        }

        // Check user credentials
        var user = db.KHACH_HANG.FirstOrDefault(kh => kh.Tai_khoan == Tai_khoan && kh.Mat_khau == Mat_khau);

        if (user != null)
        {
            FormsAuthentication.SetAuthCookie(user.Tai_khoan, false);
            return RedirectToAction("Index", "Home");
        }
        else
        {
            ModelState.AddModelError("", "Tài khoản hoặc mật khẩu không đúng");
            return View();
        }
    }

    // GET: KHACH_HANG/Logout
    public ActionResult Logout()
    {
        FormsAuthentication.SignOut();
        return RedirectToAction("Login");
    }
}

K22CNTT3-NguyenBaTruong-project2/Views/KHACH_HANG/Create.cshtml
@model K22CNTT3_NguyenBaTruong_project2.Models.KHACH_HANG

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KHACH_HANG</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ho_ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ho_ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ho_ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tai_khoan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tai_khoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tai_khoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mat_khau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mat_khau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mat_khau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dia_chi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dia_chi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dia_chi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dien_thoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dien_thoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dien_thoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngay_sinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngay_sinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngay_sinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngay_cap_nhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngay_cap_nhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngay_cap_nhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gioi_tinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gioi_tinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gioi_tinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tich_diem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tich_diem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tich_diem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trang_thai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trang_thai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trang_thai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

K22CNTT3-NguyenBaTruong-project2/Views/KHACH_HANG/Delete.cshtml
@model K22CNTT3_NguyenBaTruong_project2.Models.KHACH_HANG

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KHACH_HANG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ho_ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ho_ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tai_khoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tai_khoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mat_khau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mat_khau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dia_chi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dia_chi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dien_thoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dien_thoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngay_sinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngay_sinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngay_cap_nhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngay_cap_nhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gioi_tinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gioi_tinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tich_diem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tich_diem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trang_thai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trang_thai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

K22CNTT3-NguyenBaTruong-project2/Views/KHACH_HANG/Details.cshtml
@model K22CNTT3_NguyenBaTruong_project2.Models.KHACH_HANG

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>KHACH_HANG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ho_ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ho_ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tai_khoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tai_khoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mat_khau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mat_khau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dia_chi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dia_chi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dien_thoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dien_thoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngay_sinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngay_sinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngay_cap_nhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngay_cap_nhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gioi_tinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gioi_tinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tich_diem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tich_diem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trang_thai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trang_thai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaKH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

K22CNTT3-NguyenBaTruong-project2/Views/KHACH_HANG/Edit.cshtml
@model K22CNTT3_NguyenBaTruong_project2.Models.KHACH_HANG

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KHACH_HANG</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKH)

        <div class="form-group">
            @Html.LabelFor(model => model.Ho_ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ho_ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ho_ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tai_khoan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tai_khoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tai_khoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mat_khau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mat_khau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mat_khau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dia_chi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dia_chi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dia_chi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dien_thoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dien_thoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dien_thoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngay_sinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngay_sinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngay_sinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngay_cap_nhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngay_cap_nhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngay_cap_nhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gioi_tinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gioi_tinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gioi_tinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tich_diem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tich_diem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tich_diem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trang_thai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trang_thai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trang_thai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

K22CNTT3-NguyenBaTruong-project2/Views/KHACH_HANG/Index.cshtml
@model IEnumerable<K22CNTT3_NguyenBaTruong_project2.Models.KHACH_HANG>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ho_ten)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tai_khoan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mat_khau)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dia_chi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dien_thoai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ngay_sinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ngay_cap_nhat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gioi_tinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tich_diem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Trang_thai)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ho_ten)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tai_khoan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mat_khau)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dia_chi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dien_thoai)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ngay_sinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ngay_cap_nhat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gioi_tinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tich_diem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Trang_thai)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaKH }) |
            @Html.ActionLink("Details", "Details", new { id=item.MaKH }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaKH })
        </td>
    </tr>
}

</table>

K22CNTT3-NguyenBaTruong-project2/Views/KHACH_HANG/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm("Login", "KHACH_HANG", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label for="Tai_khoan">Tài khoản</label>
        <input type="text" name="Tai_khoan" class="form-control" required />
    </div>
    <div class="form-group">
        <label for="Mat_khau">Mật khẩu</label>
        <input type="password" name="Mat_khau" class="form-control" required />
    </div>

    <button type="submit" class="btn btn-primary">Đăng nhập</button>
}

@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <p class="text-danger">@ViewBag.ErrorMessage</p>
}

K22CNTT3-NguyenBaTruong-project2/Views/KHACH_HANG/Logout.cshtml
@if (User.Identity.IsAuthenticated)
{
    <p>Welcome, @User.Identity.Name! <a href="@Url.Action("Logout", "KHACH_HANG")">Logout</a></p>
}
else
{
    <p><a href="@Url.Action("Login", "KHACH_HANG")">Login</a></p>
}

K22CNTT3-NguyenBaTruong-project2/Views/KHACH_HANG/Register.cshtml
@model K22CNTT3_NguyenBaTruong_project2.Models.KHACH_HANG
@{
    ViewBag.Title = "Register";
}

<h2>Đăng ký tài khoản</h2>

@using (Html.BeginForm("Register", "KHACH_HANG", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Ho_ten)
        @Html.TextBoxFor(model => model.Ho_ten, new { @class = "form-control", required = "required" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tai_khoan)
        @Html.TextBoxFor(model => model.Tai_khoan, new { @class = "form-control", required = "required" })
        @Html.ValidationMessageFor(model => model.Tai_khoan)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mat_khau)
        @Html.PasswordFor(model => model.Mat_khau, new { @class = "form-control", required = "required" })
        @Html.ValidationMessageFor(model => model.Mat_khau)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email)
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", required = "required" })
        @Html.ValidationMessageFor(model => model.Email)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Dien_thoai)
        @Html.TextBoxFor(model => model.Dien_thoai, new { @class = "form-control", required = "required" })
        @Html.ValidationMessageFor(model => model.Dien_thoai)
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Đăng ký</button>
    </div>
}